Enhancement: speed-up `t8_cmesh_set_join_by_vertices`.
DLR-AMR/t8code pull request #1039
Opened 2024-04-17 15:24 UTC by jmark

**_Describe your changes here:_**

This PR aims to drastically speed-up the `t8_cmesh_set_join_by_vertices` routine via hash tables.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-04-25 11:36 UTC, Davknapp requested changes

2024-04-25 11:36 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +                               int **connectivity, const int do_both_directions)
I don't think that we should implement this option, it is somewhat unnecessary. After joining vertices the connection works in both direction, so I don't see the benefit of this option. Maybe for debugging, but then it should only be available in debug-configuration.

2024-04-29 12:00 UTC, jmark commented on benchmarks/t8_time_set_join_by_vertices.cxx
> + * The following timings are from before the performance optimization.
Fair enough. Deleted it.

2024-04-29 12:02 UTC, jmark commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +  Copyright (C) 2023 the developers
Added 2024 since this file already existed in 2023. So we copyright both years;.

2024-04-29 12:26 UTC, jmark commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +  int *conn = T8_ALLOC (int, ntrees *T8_ECLASS_MAX_FACES * 3);
In general I agree. However, this routine is already in use by C and Fortran codes. And `conn` is returned back on request. I haven't figured out a good way to return the data of a std::vector as a pointer to its data without the risk of memory corruption, memory leaks of copying.

2024-04-29 12:28 UTC, jmark commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +                               int **connectivity, const int do_both_directions)
I agree with you. This option is actually for debugging and testing purposes. It is actually used in the GoogleTests. However, changing this now would mean a breaking release. An this routine already created a live on its own and creeped into several interfaces/codes already. When we switch to proper C++/C interfaces we could clean this up.

2024-04-29 14:38 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +  int *conn = T8_ALLOC (int, ntrees *T8_ECLASS_MAX_FACES * 3);
Ok, that is understandable, we can postpone this remark then.

2024-04-30 09:29 UTC, jmark commented on src/t8_cmesh/t8_cmesh_helpers.cxx
> +                               int **connectivity, const int do_both_directions)
@Davknapp I opened an issue https://github.com/DLR-AMR/t8code/issues/1056 so we do not forget about this.

2024-05-06 07:25 UTC, Davknapp approved these changes

2024-05-06 07:25 UTC, merged