Fortran header
DLR-AMR/t8code pull request #1048
Opened 2024-04-25 04:46 UTC by chiaraMaHe

The header with the first basic functions for the Fortran interface were added and it was added to the Makefile.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-04-25 08:37 UTC, sandro-elsweijer commented on src/t8_fortran_interface/t8_fortran_interface.h
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers

```

2024-04-25 08:40 UTC, sandro-elsweijer commented
I do not know how we will finally split the C and CPP interface, but we will need a new folder structure for this. Maybe we can do it like here and have a separate API folder for every API?
https://gitlab.onelab.info/gmsh/gmsh
Then we could also add the Julia api as an optional submodule. We could do the same with the Fortran interface.

2024-06-13 09:09 UTC, sandro-elsweijer requested changes
I am not able to test the functionality, since I do not have a clue of Fortran, but it looks alright.
Btw, how does this work? These are just declarations, where are the actual definitions? And can Fortran just link to a c header file, or where are the Fortran files?

2024-06-13 09:09 UTC, sandro-elsweijer commented on api/Makefile.am
> +endif
```suggestion
endif

```

2024-06-13 09:09 UTC, sandro-elsweijer commented on api/t8_fortran_interface/t8_fortran_interface.h
> +*/
Please use docstrings here

2024-06-13 09:09 UTC, sandro-elsweijer commented on api/t8_fortran_interface/t8_fortran_interface.h
> +t8_cmesh_new_periodic_tri_wrap (sc_MPI_Comm *Ccomm);
docstring

2024-06-13 09:09 UTC, sandro-elsweijer commented on api/t8_fortran_interface/t8_fortran_interface.h
> +t8_global_productionf_noargs (const char *string);
docstrings

2024-07-12 09:14 UTC, sandro-elsweijer requested changes
Last comment :)

2024-07-12 09:14 UTC, sandro-elsweijer commented on api/t8_fortran_interface/t8_fortran_interface.h
> +*/
The docstring does not match

2024-07-15 07:05 UTC, chiaraMaHe commented
> I am not able to test the functionality, since I do not have a clue of Fortran, but it looks alright. Btw, how does this work? These are just declarations, where are the actual definitions? And can Fortran just link to a c header file, or where are the Fortran files?

This is only the c header file, that will be imported into a c file, which defines functions that are needed by the f90 file. It makes it easier because you sometimes need to pass the pointer instead of the value (Ccomm). The c-file and the f90 file will follow in the upcoming PRs

2024-07-15 07:43 UTC, sandro-elsweijer approved these changes

2024-07-15 07:43 UTC, sandro-elsweijer commented on api/t8_fortran_interface/t8_fortran_interface.h
> +
```suggestion

```

2024-07-16 12:01 UTC, sandro-elsweijer approved these changes
Almost

2024-07-16 12:07 UTC, merged