Feature multiple attributes ghost commit from stash
DLR-AMR/t8code pull request #1173
Opened 2024-07-22 08:16 UTC by lukasdreyer

**_Describe your changes here:_**

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-07-22 09:19 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +* Return > 0 if >
```suggestion
* Return True if global_id of if_A < global_id of id_B
* Return False otherwise
```

2024-07-22 09:19 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +* Return > 0 if >
```suggestion
* Return True if local id of if_A < local id of id_B
* Return False otherwise
```

2024-07-22 13:06 UTC, holke commented
Needs to be cleaned up.
There are still debug statements and comments that should be cleaned up.

2024-07-22 13:11 UTC, holke commented
Closes #1114

2024-07-22 13:58 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +  t8_debugf ("DONE\n");
```suggestion
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    t8_debugf ("Size of tree attributes: %li\n", tree->num_attributes * sizeof (t8_attribute_info_struct_t));
```suggestion
    next_tree_offset
      = tree->att_offset + tree->num_attributes * sizeof (t8_attribute_info_struct_t) - sizeof (t8_ctree_struct_t);
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +  t8_debugf ("Size of tree: %li\n", sizeof (t8_ctree_struct_t));
```suggestion
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +  t8_debugf ("first_ghost_offset %li\n", first_ghost_offset);
```suggestion
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    t8_debugf ("global id of ghost %li\n", ghost->treeid);
```suggestion
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    t8_debugf ("temp_offset %li\n", temp_offset);
```suggestion
```

2024-07-22 13:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    t8_debugf ("num_attributes_of_ghosts[it].num_attributes %i\n", num_attributes_of_ghosts[it].num_attributes);
```suggestion
```

2024-07-22 14:01 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    t8_debugf ("set attr_offset: %li\n", attr->attribute_offset);
```suggestion
```

2024-07-22 14:01 UTC, holke commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +  //attr_info->attribute_offset = *attribute_data_offset;
```suggestion
```

2024-07-22 14:01 UTC, holke commented on src/t8_geometry/t8_geometry_with_vertices.cxx
> +
```suggestion
```

2024-07-22 14:01 UTC, holke commented on test/t8_cmesh/t8_gtest_cmesh_partition.cxx
> +      //      GTEST_SKIP ();
```suggestion
```

2024-08-12 13:41 UTC, jmark requested changes

2024-08-12 13:41 UTC, jmark commented on test/t8_cmesh/t8_gtest_cmesh_partition.cxx
>      if (found != std::string::npos) {
This empty if-statement can probably be deleted completely.

2024-08-12 13:41 UTC, jmark commented on src/t8_cmesh/t8_cmesh_trees.h
> + * TODO: Document
Please find the time and motivation to clear this todo. :)

2024-08-12 13:41 UTC, jmark commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +    //    t8_debugf("size of array:%li, offset: %li", first_face + attr_total_bytes + face_neigh_bytes, )
```suggestion
```

2024-08-12 13:41 UTC, jmark commented on src/t8_cmesh/t8_cmesh_trees.cxx
> +#if 0
What is this dead code doing here? Please either delete it or turn it into a code segment for debug mode.

2024-08-12 13:42 UTC, jmark commented
@lukasdreyer Thank you for your work on this PR! Please see the review comments above. Also please resolve the merge conflict.

2024-09-23 10:09 UTC, merged