Fortran auto-build
DLR-AMR/t8code pull request #1182
Opened 2024-07-24 10:01 UTC by chiaraMaHe

Auto-Build system for the Fortran interface. 
Use --enable-fortran while configure

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-08-13 12:13 UTC, holke requested changes
Looks good.
I can configure and build with and without enable-fortran.
The fortran interface is build.

Only one question:
Is this commented out intentionally?
"#include t8_fortran_specific.mk"

2024-08-13 12:16 UTC, holke commented
[ ] Should this use case be added to the github action?

Yes it should, i would propose to activate "enable-fortran" in all test cases by default.
will open a new issue.

2024-08-19 06:47 UTC, sandro-elsweijer commented on api/Makefile.am
> +endif
```suggestion
endif

```
newline at eof

2024-08-19 06:58 UTC, chiaraMaHe commented on api/t8_fortran_interface/t8_mo_fortran_interface.f90
it stands for 'module'. There was an error because there were two files with the name t8_fortran_interface.f90 in the old version and so it was named with the mo inside of the name. However, as there is now only one file with this name, I can change that

2024-08-19 07:28 UTC, chiaraMaHe commented on api/Makefile.am
> +#include t8_fortran_specific.mk
The f90 file is still empty and filled in the next PR, but as I added the empty file, it can be uncommented

2024-09-24 16:51 UTC, jmark commented
This PR is now covered by: https://github.com/DLR-AMR/t8code/pull/1255

2024-09-24 16:51 UTC, closed without merging