Pack/Unpack data for user-data
DLR-AMR/t8code pull request #1224
Opened 2024-08-20 08:08 UTC by Davknapp

An interface for arbitrary data that. 
For new user-data it suffies to implement how a single element should be packed/unpacked. 
The routines for vectors of user-data make use of this routine and pack/unpack the data accordingly. 

Furthermore it provides a wrapper around the send/recv routine from MPI for to avoid code duplication and easy usage. This part of the interface should be extended in the future to other MPI send/recv routines. 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-10-01 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_pseudo_trees.hxx
> +
file documentation

2024-10-01 11:47 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  pack_vector_prefix (void *buffer, const int num_bytes, int &pos, sc_MPI_Comm comm)
No, because the buffer used by MPI is a void* buffer. We want to pass this buffer to the MPI-function and it expects a void *

2024-10-01 11:48 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  virtual int
This is currently more a place-holder than a proper implementation. An enum over all of our types that can be used by this class would be nice.

2024-10-01 11:49 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  buffer_size (sc_MPI_Comm comm) override
It is documented in its parent-class

2024-10-01 11:49 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  pack_vector_prefix (void *buffer, const int num_bytes, int &pos, sc_MPI_Comm comm) override
This function has documentation in its parent class

2024-10-01 11:49 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  unpack_vector_prefix (const void *buffer, const int num_bytes, int &pos, int &outcount, sc_MPI_Comm comm) override
This function has documentation in its parent class

2024-10-01 11:49 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  send (const int dest, const int tag, sc_MPI_Comm comm) override
This function has documentation in its parent class

2024-10-01 11:51 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  recv (const int source, const int tag, sc_MPI_Comm comm, sc_MPI_Status *status, int &outcount) override
This function is documented in its parent-class

2024-10-01 11:51 UTC, Davknapp commented on src/t8_data/t8_data_handler.hxx
> +  type () override
This function is documented in its parent-class

2024-10-01 11:55 UTC, Davknapp commented on src/t8_data/t8_data_handler_base.hxx
> +class t8_single_data_handler {
Because it used to pack/unpack/handle a single data-item

2024-10-01 13:24 UTC, Davknapp commented on test/t8_data/t8_data_handler_specs.hxx
> +    check = check;
yes, I am sorry, fixed it

2025-01-03 14:41 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +  pack_vector_prefix (void *buffer, const int num_bytes, int &pos, sc_MPI_Comm comm)
:(

2025-01-03 14:42 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +   * \param[in] pos A reference to an integer representing the current position in the buffer. This will be updated as bytes are packed.
Isn't it then [in, out]?

2025-01-03 14:42 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +  virtual int
Do you want to add a TODO?

2025-01-03 15:05 UTC, sandro-elsweijer requested changes
Maybe its just a pet peeve of mine, but none of your docstrings is indented

2025-01-03 15:05 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +Copyright (C) 2024 the developers
```suggestion
Copyright (C) 2025 the developers
```

Happy New Year 🥳

2025-01-03 15:05 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler_base.hxx
> +
For all files, the other formats are also off

2025-01-03 15:05 UTC, sandro-elsweijer commented on test/t8_data/t8_gtest_data_handler.cxx
> +template <typename T>
Please rename the parameter

2025-01-28 08:18 UTC, Davknapp commented
A C-interface will be implemented in #1357

2025-01-31 11:38 UTC, sandro-elsweijer approved these changes
Minor comments about the docstring style

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_packs/t8_enlarged_stdtypes.hxx
> + * \brief A template specialisation for handling single enlarged ints (int plus an additional int, this
```suggestion
 * A template specialisation for handling single enlarged ints (int plus an additional int, this 
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_packs/t8_enlarged_stdtypes.hxx
> + * \brief pseudo_types for testing
```suggestion
 * pseudo_types for testing
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler_base.hxx
> + * \brief A template class for handling single data items.
```suggestion
 * Template class for handling single data items.
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +  * \brief A shared pointer to a vector of data.
```suggestion
  * A shared pointer to a vector of data. 
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +   * \brief A single data handler for the data type T.
```suggestion
   * A single data handler for the data type T.
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +   * \brief Get the data.
```suggestion
   * Get the data.
```

2025-01-31 11:38 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> + * \brief A template class for handling data in a distributed environment.
```suggestion
 * A template class for handling data in a distributed environment.
```

2025-02-18 15:00 UTC, sandro-elsweijer requested changes
The documentation is still inconsistent or missing

2025-02-18 15:00 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * TODO: implement a proper type/enum for this.
Please create an Issue for this or solve this todo

2025-02-18 15:00 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +  }
I know that there are docstrings in the abstract base, but these will only be shown if the object is casted into a pointer of that object. This class will not show any docstrings

2025-02-18 15:00 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +inline t8_abstract_vector_handler *
docstring

2025-02-18 15:00 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.cxx
> +}
docstrings

2025-02-18 15:00 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> + * \file t8_data_handler.hxx
wrong order

2025-02-18 15:00 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.hxx
> + * \file This file provides a templated class that enlarges a data type by a check-int.
Filename is missing, wrong order

2025-02-19 09:41 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> + * \return false otherwise
```suggestion
 * \return True if the type is handled internally, false otherwise
```

2025-02-19 09:42 UTC, sandro-elsweijer commented on src/t8_data/t8_data_handler.hxx
> +   * Construct a new t8 single data handler.
```suggestion
   * Construct a t8_data_handler.
```

2025-02-19 09:43 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * Construct a new t8 data handler.
```suggestion
   * Construct a t8_vector_handler.
```

2025-02-19 09:44 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * Construct a new t8 data handler with the given data.
```suggestion
   * Construct a t8_vector_handler with the given data.
```

2025-02-19 09:44 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * \return std::shared_ptr<std::vector<TType>>
```suggestion
   * \return The data.
```

2025-02-19 09:44 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * \return int The size of the buffer.
```suggestion
   * \return The size of the buffer.
```

2025-02-19 09:45 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> +   * \return constexpr t8_data_handler_type
?

2025-02-19 09:45 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> + * \return t8_abstract_vector_handler* A handler for the given data type.
```suggestion
 * \return A handler for the given data type.
```

2025-02-19 09:45 UTC, sandro-elsweijer commented on src/t8_data/t8_vector_handler.hxx
> + * \param[in] type
?

2025-02-19 09:46 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.hxx
> + */
???

2025-02-19 09:47 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.hxx
> + * \tparam TType
?

2025-02-19 09:47 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.cxx
> + * \tparam              enlarged_data<double>
?

2025-02-19 09:47 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.cxx
> + * \tparam              enlarged_data<int>
?

2025-02-19 09:48 UTC, sandro-elsweijer commented on test/t8_data/t8_gtest_data_handler.cxx
> + * @tparam T the type of data
?

2025-02-19 09:49 UTC, sandro-elsweijer commented on test/t8_data/t8_pseudo_trees.hxx
> + * pseudo_tree
```suggestion
```

2025-02-19 11:28 UTC, Davknapp commented on test/t8_data/t8_data_handler_specs.hxx
> + */
What is bothering you there?

2025-06-16 11:20 UTC, sandro-elsweijer requested changes

2025-06-16 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.hxx
> + */
We never use \var in this context.
The arguments should be in the docstring of the constructor and not the class. A class can have multiple constructors, so this way does not work.

2025-06-16 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_data_handler_specs.hxx
> +  enlarged_data (TType data, int check): data (data), check (check)
Docstring

2025-06-16 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_enlarged_stdtypes.hxx
> + */
This class is not called `t8_single_data_handler`
```suggestion
/**
 * A template specialization for handling single enlarged doubles (double plus an additional int, this 
 * data-type is meant for testing).
 * 
 * This class implements methods for packing, unpacking, and determining the size of single data items.
 * 
 */
```

2025-06-16 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_enlarged_stdtypes.hxx
> +#define T8_ENLARGED_STDTYPES
```suggestion
#ifndef T8_ENLARGED_STDTYPES_HXX
#define T8_ENLARGED_STDTYPES_HXX
```

2025-06-16 11:20 UTC, sandro-elsweijer commented on test/t8_data/t8_enlarged_stdtypes.hxx
> +#endif /* T8_ENLARGED_STDTYPES */
```suggestion
#endif /* T8_ENLARGED_STDTYPES_HXX */
```

2025-06-23 06:03 UTC, sandro-elsweijer approved these changes

2025-06-23 07:56 UTC, merged