Package source files and update actions
DLR-AMR/t8code pull request #1254
Opened 2024-09-24 13:23 UTC by Davknapp

Use CPack to create a target to package source files (binary packaging will not be supported by this)

Furthermore a github action is added to check the proper creation of the tar-ball. 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-09-26 15:31 UTC, jmark requested changes
On my machine the "version.txt" file is not created.

I'm using cmake version 3.23.1.

2024-09-27 06:49 UTC, Davknapp commented
The version file is created automatically when the code is compiled. If you only want to pack it, it has to be triggered manually

2024-09-27 10:22 UTC, jmark requested changes
LGTM! Nice work! Just have a minor suggestion.

2024-09-27 10:22 UTC, jmark commented on CMakeLists.txt
> +include (CPackConfig.cmake)
Minor suggestion. Moving this script into the `cmake` folder.
```suggestion
include (cmake/CPackConfig.cmake)
```

2024-09-27 11:35 UTC, jmark approved these changes

2024-09-27 11:37 UTC, merged

2024-10-28 14:45 UTC, sandro-elsweijer commented on .github/workflows/build_cmake_tarball.yml
> +# Setup and bootstrap
no bootstrap

2024-10-28 14:46 UTC, sandro-elsweijer commented on .github/workflows/build_cmake_tarball.yml
> +      run: ./bootstrap
not needed

2024-10-28 14:47 UTC, sandro-elsweijer commented on .github/workflows/build_cmake_tarball.yml
> +      run: export CONFIG_OPTIONS="${LESS_TEST_OPTION} -GNinja -DT8CODE_USE_SYSTEM_SC=OFF -DT8CODE_USE_SYSTEM_P4EST=OFF -DT8CODE_BUILD_PEDANTIC=ON -DT8CODE_ENABLE_MPI=$MPI -DCMAKE_BUILD_TYPE=$BUILD_TY
This does not work, since there are no inputs to this script

2024-10-28 14:48 UTC, sandro-elsweijer commented on .github/workflows/build_cmake_tarball.yml
> +      run: pandoc --version
put this to the setup please

2024-10-28 14:49 UTC, sandro-elsweijer commented on .github/workflows/build_cmake_tarball.yml
> +  workflow_dispatch:
please put this workflow to the other cmake workflows just like the t8code_w_shipped_submodules test