Disable build noise from sc and p4est
DLR-AMR/t8code pull request #1283
Opened 2024-10-29 16:12 UTC by dutkalex

**_Describe your changes here:_**
Until very recently, the building of the numerous examples and tests of both libsc and p4est couldn't be disabled in downstream projects. This PR addresses this issue to provide cleaner and faster t8code builds.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [x] The author added a BSD statement to `doc/` (or already has one)

2024-11-04 14:23 UTC, sandro-elsweijer commented
Hey @dutkalex,
thank you for this contribution. This definitely solves a problem I also have!
But as you have seen, we use MPI datatypes which SC removed and this is the reason why we cannot update SC at the time.
There is an open [discussion](https://github.com/cburstedde/libsc/issues/204) about that and as soon as it is resolved, we can update SC and deactivate the p4est and SC tests for t8code.

For now you can also run the tests with `ctest -R t8_` to only run the t8code tests. If you want to run them in parallel, you can do `ctest -j<num_procs/num_opened_mpi_ranks> -R _parallel; ctest -j<num_procs> -R _serial`. We have this distinction because the parallel tests spawn multiple processes.

2024-11-04 14:30 UTC, dutkalex commented
Hmm... this explains that. 
Thanks for letting me know @sandro-elsweijer. As this is not a "hard problem" but merely a convenience thing, it can wait until libsc checks all the boxes to make a safe upgrade

2025-01-03 14:36 UTC, sandro-elsweijer commented
@dutkalex A quick update: It seems like our requests were adapted in SC and @lukasdreyer will take a look at it. We will inform you when we update our SC submodule :)

And happy new year!

2025-01-13 12:46 UTC, sandro-elsweijer commented
@dutkalex Okay you should be able to bump to the newest SC version now. This should then also work with the MPI datatypes and you can remove your MPI changes.

2025-01-16 15:12 UTC, lukasdreyer commented on CMakeLists.txt
> +option( T8CODE_BUILD_DOCUMENTATION "Build t8code's documentation" OFF )
I assume you only wanted to include the `cmake_dependent_option` here, but accidentally duplicated some of the `option` calls.

2025-01-16 15:15 UTC, lukasdreyer commented
closes #1109

2025-01-16 15:34 UTC, dutkalex commented on CMakeLists.txt
> +option( T8CODE_BUILD_DOCUMENTATION "Build t8code's documentation" OFF )
Hi @lukasdreyer , which option is duplicated exactly ? I don't see it, or maybe I'm misunderstanding your remark

2025-01-16 15:37 UTC, lukasdreyer commented on CMakeLists.txt
> +option( T8CODE_BUILD_DOCUMENTATION "Build t8code's documentation" OFF )
T8CODE_BUILD_AS_SHARED_LIBRARY is already defined in line 15, T8CODE_BUILD_PEDANTIC in line 16

2025-01-16 18:26 UTC, dutkalex commented on CMakeLists.txt
> +option( T8CODE_BUILD_DOCUMENTATION "Build t8code's documentation" OFF )
Thanks. Turns out `T8CODE_EXPORT_COMPILE_COMMANDS` was also duplicated...

2025-01-20 15:21 UTC, lukasdreyer requested changes
Just a few duplicated option calls left, otherwise a nice addition

2025-01-20 15:21 UTC, lukasdreyer commented on CMakeLists.txt
> +option( T8CODE_BUILD_TESTS "Build t8code's automated tests" ON )
still duplicated

2025-01-20 15:21 UTC, lukasdreyer commented on CMakeLists.txt
> +option( T8CODE_BUILD_EXAMPLES "Build t8code's examples" ON )
still duplicated

2025-01-20 15:21 UTC, lukasdreyer commented on CMakeLists.txt
> +option( T8CODE_BUILD_FORTRAN_INTERFACE "Build t8code's Fortran interface" OFF )
still duplicated

2025-01-20 16:09 UTC, dutkalex commented
Hope I fixed them all them all this time. Thanks for catching that @lukasdreyer

2025-01-20 16:22 UTC, lukasdreyer commented on CMakeLists.txt
> +    set( SC_BUILD_EXAMPLES ${T8CODE_BUILD_TPL_EXAMPLES} )
Do I understand this correctly that `T8CODE_BUILD_TPL_EXAMPLES` overwrites `SC_BUILD_EXAMPLES`?
So setting `T8CODE_BUILD_EXAMPLES` to OFF disables t8code, sc and p4est examples?

2025-01-20 16:23 UTC, lukasdreyer commented
> Hope I fixed them all them all this time. Thanks for catching that @lukasdreyer

Looks much better now!

2025-01-20 16:31 UTC, dutkalex commented on CMakeLists.txt
> +    set( SC_BUILD_EXAMPLES ${T8CODE_BUILD_TPL_EXAMPLES} )
This was the intent yes. I couldn't think of a scenario where you wouldn't want to build t8code's examples but you'd still want to build those of libsc or p4est.

2025-01-20 16:32 UTC, lukasdreyer commented on CMakeLists.txt
> +    set( SC_BUILD_EXAMPLES ${T8CODE_BUILD_TPL_EXAMPLES} )
This sounds like a very useful addition to the build system!

2025-01-20 16:33 UTC, lukasdreyer approved these changes

2025-01-20 16:41 UTC, merged