add interface for replicated partition search
DLR-AMR/t8code pull request #1286
Opened 2024-10-30 14:41 UTC by hannesbrandt

**_Describe your changes here:_**
Add an interface for the partition search of a forest with replicated coarse mesh.
The interface coincides with the local search in large parts. The parameters `is_leaf, leaf_elements` and `tree_leaf_index` are not available in the partition search and are replaced with the process range `[pfirst,plast]`. Although all global trees are going to be traversed through use of the replicated coarse mesh, the tree id is provided as a `t8_locidx_t` as this matches the input parameters of `t8_cmesh_get_tree_class`.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-10-31 09:41 UTC, holke commented
Thank you for posting the PR.
We will have a look at it and provide feedback.

2024-11-05 09:13 UTC, Davknapp requested changes
Thanks for your Draft PR. it is looking good so far, we will discuss it further! 
Can you add an author-file to /doc in the meantime?

2024-11-05 09:13 UTC, Davknapp commented on src/t8_forest/t8_forest_iterate.h
> + * \param[in] pfirst              the lowest processor that owns part of \a element. Guaranteed to be non-empty.
```suggestion
 * \param[in] pfirst              the first processor that owns part of \a element. Guaranteed to be non-empty.
```

2024-11-05 09:13 UTC, Davknapp commented on src/t8_forest/t8_forest_iterate.h
> + * \param[in] plast               the highest processor that owns part of \a element. Guaranteed to be non-empty.
```suggestion
 * \param[in] plast               the last processor that owns part of \a element. Guaranteed to be non-empty.
```

2024-11-05 12:54 UTC, hannesbrandt commented on src/t8_forest/t8_forest_iterate.h
> +t8_forest_search_partition (t8_forest_t forest, t8_forest_partition_search_fn search_fn,
I've updated this. The forest parameter in `t8_forest_search` is not defined as const, should I change this as well?

2024-11-05 12:55 UTC, hannesbrandt commented
Thank you for the feedback. I have added my author.txt and implemented your suggestions.

2024-11-07 09:01 UTC, Davknapp commented
> Thank you for the feedback. I have added my author.txt and implemented your suggestions.

Thank you! We are currently upgrading t8code to support C++17-features and want knew features to support this standart from the beginning on. We discuss what this means in detail for your feature and will keep you updated!

2024-11-19 14:29 UTC, Davknapp commented
Hey @hannesbrandt 

we've worked on a cpp-interface for our current search-algorithms, which you can find in: 
https://github.com/DLR-AMR/t8code/pull/1297

Could you go in a similar direction with your implementation, please?

2024-12-09 16:41 UTC, hannesbrandt commented
I've added a cpp-interface for the partition search similar to the interface for the local search. Does this match your idea of what the interface should look like? 
I've merged the changes from the not-yet-merged PR https://github.com/DLR-AMR/t8code/pull/1297 to ensure a consistent file structure.

2025-01-10 08:40 UTC, Davknapp commented
> I've added a cpp-interface for the partition search similar to the interface for the local search. Does this match your idea of what the interface should look like? I've merged the changes from the not-yet-merged PR #1297 to ensure a consistent file structure.

Sorry for the late reply and thank you for your changes! We will have a look at it soon. For the future can you assign the reviewer again to the PR as soon as you have finished another round in our review process? We might have missed this part in our developer guidelines, I have just updated them so we won't let you wait this long again.

2025-01-28 16:44 UTC, Davknapp commented
> Hey @Davknapp, I have updated my branch to the most recent main.

Perfect, I will have a detailed look at it tomorrow morning!

2025-01-29 08:00 UTC, Davknapp commented on src/t8_forest/t8_forest_iterate.cxx
> +  T8_ASSERT (0); /* not implemented yet */
```suggestion
  SC_ABORT ("not implemented yet");
```

2025-01-29 08:00 UTC, Davknapp reviewed
Looks good in general, ´please address my only remaining comment.

2025-01-29 11:32 UTC, merged