Fix: More robust connect cmesh faces by vertices and sphere cmesh examples
DLR-AMR/t8code pull request #1296
Opened 2024-11-06 16:23 UTC by jmark

**_Describe your changes here:_**

This PR introduces fixes/enhancements to make the `join_by_vertices` routine more robust regarding the value range of the input vertices. Besides that this PR makes the sphere cmesh examples more robust by applying the actual radius parameter at the end when the vertex information is stored in the cmesh object. For some use cases the radius gets extremely big, e.g. around 1e6, and the shell thickness, quite small, e.g. around 10. This might confuse the `join_by_vertices` routine. The fix is to determine the face connectivity on a reference sphere/shell with sane radius/thickness.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-11-18 11:43 UTC, Davknapp commented
> @Niklas997 @Davknapp
> 
> Do you need any input in order to progress on the review? Please agree on who feels responsible for doing the review.

I will do it

2024-11-18 12:33 UTC, Davknapp requested changes
Some small changes, then we can merge.

2024-11-18 12:33 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_examples.cxx
>    int itree = -1;
```suggestion
```

2024-11-18 12:33 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_examples.cxx
>    for (int turn = 0; turn < ntrees / 2; turn++) {
```suggestion
  for (int turn = 0, itree = -1; turn < ntrees / 2; turn++) {
```

2024-11-18 12:33 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_examples.cxx
>    int itree = -1;
```suggestion
```

2024-11-18 12:33 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_examples.cxx
>    for (int turn = 0; turn < 5; turn++) {
```suggestion
  for (int turn = 0, itree = -1; turn < 5; turn++) {
```

2024-11-18 12:33 UTC, Davknapp commented on src/t8_cmesh/t8_cmesh_examples.cxx
>    for (int turn = 0; turn < 5; turn++) {
Please update these changes to the similar loops.

2024-11-19 12:40 UTC, jmark commented
> Some small changes, then we can merge.

I like it! Done.

2024-11-19 14:24 UTC, Davknapp approved these changes

2024-11-19 14:24 UTC, merged