Update vec
DLR-AMR/t8code pull request #1307
Opened 2024-11-20 11:00 UTC by ole-alb

**_Describe your changes here:_**

Update the vector functions to use the standard library. 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [ ] The author added a BSD statement to `doc/` (or already has one)

2025-02-14 10:27 UTC, Davknapp reviewed
I suggested to make some functions constexpr. Please try it, I am not 100% about every possibility.

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline double
```suggestion
constexpr double
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline bool
```suggestion
constexpr bool
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-14 10:27 UTC, Davknapp commented on src/t8_types/t8_vec.hxx
> +static inline void
```suggestion
constexpr void
```

2025-02-17 12:00 UTC, ole-alb commented on src/t8_types/t8_vec.hxx
> +static inline double
Not possible here

2025-02-17 12:01 UTC, ole-alb commented on src/t8_types/t8_vec.hxx
> +static inline void
Not possible here

2025-02-20 09:21 UTC, Davknapp requested changes
Thanks for all the changes that you already made! I know this is again a lot of work, but it is very appreciated!

2025-02-20 09:21 UTC, Davknapp commented on src/t8_types/t8_type.hxx
> +#include <functional>
```suggestion
```
This is the only change in this file. So I guess we don't need it?

2025-02-20 09:21 UTC, Davknapp commented on src/t8_vtk/t8_vtk_writer.hxx
> +#include <t8_element.h>
Why did you need to add t8_element.h?

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +                          t8_vec<24> test_return_coords)
```suggestion
                          const t8_vec<24> &test_return_coords)
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +  t8_vec<24> surface_test_return_coords ({ 0.0396282769,  0.1897542602, 0.0396282769,
```suggestion
  const t8_vec<24> surface_test_return_coords ({ 0.0396282769,  0.1897542602, 0.0396282769, 
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +  t8_vec<24> curve_test_return_coords ({ 0.0955204602, 0.2235162028, 0.1217553783,
```suggestion
  const t8_vec<24> curve_test_return_coords ({ 0.0955204602, 0.2235162028, 0.1217553783, 
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +                          t8_vec<dimension> &test_return_coords)
```suggestion
t8_test_geometry_cad_tet (const int face, const int edge, double *parameters, double *test_ref_coords,
                          const t8_vec<dimension> &test_return_coords)
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +  t8_vec<12> surface_test_return_coords
```suggestion
  const t8_vec<12> surface_test_return_coords
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +                            t8_vec<dimension> &test_return_coords)
```suggestion
t8_test_geometry_cad_prism (const int face, const int edge, double *parameters, double *test_ref_coords,
                            const t8_vec<dimension> &test_return_coords)
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +  t8_vec<12> surface_test_return_coords_quad
```suggestion
  const t8_vec<12> surface_test_return_coords_quad
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +  t8_vec<9> surface_test_return_coords_tri
```suggestion
  const t8_vec<9> surface_test_return_coords_tri
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +      t8_vec<12> surface_test_return_coords = surface_test_return_coords_quad;
```suggestion
      const t8_vec<12> surface_test_return_coords = surface_test_return_coords_quad;
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_cad.cxx
> +      t8_vec<9> surface_test_return_coords = surface_test_return_coords_tri;
```suggestion
      const t8_vec<9> surface_test_return_coords = surface_test_return_coords_tri;
```

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_lagrange.cxx
> +#include <t8_element.h>
Why do you need t8_element.h?

2025-02-20 09:21 UTC, Davknapp commented on test/t8_geometry/t8_gtest_point_inside.cxx
> +  const int num_points_to_generate = 16384; /* Desired number of test points per element.
```suggestion
  const int num_points_to_generate = 64; /* Desired number of test points per element. 
```
This should stay unchanged.

2025-02-20 09:21 UTC, Davknapp commented on test/t8_schemes/t8_gtest_element_ref_coords.cxx
> +#include <t8_element.h>
```suggestion
```

2025-02-20 12:11 UTC, ole-alb commented on src/t8_types/t8_type.hxx
> +#include <functional>
I somehow can't compile without it

2025-02-20 12:58 UTC, ole-alb commented on src/t8_types/t8_operators.hxx
> +/**
Implemented in PR #1421

2025-02-21 08:30 UTC, Davknapp requested changes
Just one small (but hopefully quick) change and we are ready to merge!

2025-02-21 08:30 UTC, Davknapp commented on example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
> +    *h = sqrt (t8_dot (corner[0], corner[0]));
Can you put this into a new vector function t8_length?

2025-02-21 08:30 UTC, Davknapp commented on src/t8_types/t8_operators.hxx
> +/**
Thank you!

2025-02-21 09:00 UTC, Davknapp commented on example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
> +    *h = sqrt (t8_dot (corner[0], corner[0]));
as you just mentioned - we already have the function t8_norm. That one should be used here ;)

2025-02-21 09:02 UTC, Davknapp commented on example/IO/cmesh/gmsh/t8_load_and_refine_square_w_hole.cxx
> +      *h = SC_MAX (sqrt (t8_dot (corner[i], corner[i])), *h);
```suggestion
      *h = SC_MAX (sqrt (t8_norm (corner[i])), *h);
```

2025-02-21 09:04 UTC, Davknapp requested changes
one tiny last thing

2025-02-21 09:14 UTC, Davknapp approved these changes

2025-02-21 10:20 UTC, merged