Standalone scheme
DLR-AMR/t8code pull request #1331
Opened 2024-12-20 14:45 UTC by ole-alb

**_Describe your changes here:_**

Create a new standalone scheme

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### License

- [ ] The author added a BSD statement to `doc/` (or already has one)

#### Tag Label

- [ ] The author added the patch/minor/major label in accordance to semantic versioning.

2025-01-13 14:20 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone.cxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2025 the developers
```

2025-01-13 14:21 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2025 the developers
```

2025-01-13 14:22 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +#define t8_standalone_element_t t8_standalone_t
```suggestion
#define t8_standalone_element t8_standalone
```

2025-01-13 14:23 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +typedef int8_t t8_cube_id_t;
```suggestion
typedef uint32_t t8_element_coord;
typedef uint8_t t8_element_level;
typedef int8_t t8_cube_id;
```

2025-01-13 14:23 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2025 the developers
```

2025-01-13 14:23 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +#define T8_STANDALONE_ELEMENT_CXX_HXX
```suggestion
#ifndef T8_STANDALONE_ELEMENT_HXX
#define T8_STANDALONE_ELEMENT_HXX
```

2025-01-13 14:24 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  void *ts_context;    /**< Anonymous implementation context. */
```suggestion
  void *scheme_context;    /**< Anonymous implementation context. */
```

2025-01-13 14:25 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   *                        or 1 (both faces have the same top. orientattion).
```suggestion
   *                        or 1 (both faces have the same top. orientation).
```

2025-01-13 14:25 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +#endif /* T8_STANDALONE_ELEMENT_CXX_HXX */
```suggestion
#endif /* T8_STANDALONE_ELEMENT_HXX */
```

2025-01-13 14:26 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +struct t8_standalone_element_t
```suggestion
struct t8_standalone_element
```

2025-01-13 14:27 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +#ifndef T8_STANDALONE_ELEMENTS_HXX
To stay consisten, we should use the singular `element` in the filename

2025-01-13 14:27 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone.hxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2025 the developers
```

2025-01-13 14:28 UTC, sandro-elsweijer commented
I just found the PR interesting and when something stood out I marked it already :)

2025-01-14 12:22 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +#ifndef T8_STANDALONE_ELEMENTS_HXX
I think this approach should also work. The one where I used `...ELEMENT_CXX_HXX` shouldn't even be `element`, it should rather be `implementation`.

2025-01-15 12:48 UTC, sandro-elsweijer reviewed
When https://github.com/DLR-AMR/t8code/pull/1341 is merged into main and you update this branch, these changes will adapt your branch to the changes in https://github.com/DLR-AMR/t8code/pull/1341.

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      eclass (TEclass) {};
```suggestion
  t8_standalone_scheme ()
    : element_size (sizeof (t8_standalone_element<TEclass>)), scheme_context (sc_mempool_new (element_size)) {};
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  /** Destructor for all default schemes */
```suggestion
 public:
  /** Destructor for all default schemes */
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    : element_size (other.element_size), scheme_context (other.scheme_context), eclass (other.eclass)
```suggestion
    : element_size (other.element_size), scheme_context (other.scheme_context)
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      eclass = other.eclass;
```suggestion
      element_size = other.element_size;
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    : element_size (other.element_size), scheme_context (sc_mempool_new (other.element_size)), eclass (other.eclass) {};
```suggestion
  t8_standalone_scheme (const t8_standalone_scheme &other)
    : element_size (other.element_size), scheme_context (sc_mempool_new (other.element_size)) {};
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      eclass = other.eclass;
```suggestion
      element_size = other.element_size;
```

2025-01-15 12:48 UTC, sandro-elsweijer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +
```suggestion

  /** Return the tree class of this scheme.
   * \return The tree class of this scheme.
   */
  inline t8_eclass_t
  get_eclass (void) const
  {
    return TEclass;
  }

```

2025-01-16 08:39 UTC, lukasdreyer requested changes
Found a few things

2025-01-16 08:39 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +//constexpr uint8_t T8_ELEMENT_MAXLEVEL[T8_ECLASS_COUNT] = {2, 2, 2, 2, 2, 2, 2, 2};
Remove these or comment the usecase

2025-01-16 08:39 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +  t8_element_type<TEclass> type;
Is the type currently used anywhere? Except for setting it to zero in root and printing it and helper functions?
I would remove it for this PR, as the type is only used for non hypercube elements

2025-01-16 08:39 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
Not yet relevant

2025-01-16 08:39 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
Not yet relevant

2025-01-16 08:39 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  }
No longer needed with iterative linear id functions

2025-01-16 12:26 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +// #include "t8_sele_lut_tet_cxx.hxx"
Not yet needed

2025-01-16 13:10 UTC, lukasdreyer approved these changes

2025-01-16 14:01 UTC, lukasdreyer commented
Please have a look if some of the forest tests can already be run with the standalone scheme

2025-01-16 15:32 UTC, ole-alb commented
The forest tests: ´t8_gtest_element_if_leaf`, `t8_gtest_partition_data` and t8_gtest_usesr_data` already run with the current state of the standalone scheme.

2025-01-17 11:29 UTC, Davknapp requested changes
This is a first look at the PR, I still need to look at the other files! But so far: Thank you for the good work!.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      t8_linearidx_t num_descendants_of_child = 0;
```suggestion
```
The scope of num_descendants_of_child is actually inside the while loop so it can be removed here.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        num_descendants_of_child = t8_standalone_scheme<TEclass>::element_count_leaves ((t8_element_t *) &child, level);
```suggestion
        const t8_lindearidx_t num_descendants_of_child = t8_standalone_scheme<TEclass>::element_count_leaves ((t8_element_t *) &child, level);
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        t8_linearidx_t sum_descendants_of_children_until_current
```suggestion
        const t8_linearidx_t sum_descendants_of_children_until_current
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      while (true) {
This is not good praxis in my opinion. please move the breaking condition (currently line 914) into the condition part.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_get_linear_id (const t8_element_t *elem, int level)
```suggestion
  element_get_linear_id (const t8_element_t *elem, const int level)
```
please check, that elem is valid on input.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    int id = 0;
```suggestion
    t8_lindearidx_t id = 0;
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        t8_standalone_element<TEclass> child;
Please allocate child outside of both loops. Otherwise we allocate an element a lot of times, even though we only use it as a placeholder.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        t8_standalone_element<TEclass> child;
please allocate the child outside of both loops. Otherwise we allocate it a lot of times, which probably is expensive.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        t8_linearidx_t num_child_descendants
```suggestion
        const t8_linearidx_t num_child_descendants
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_count_leaves (const t8_element_t *elem, int level)
```suggestion
  element_count_leaves (const t8_element_t *elem, const int level)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  count_leaves_from_root (int level)
```suggestion
  count_leaves_from_root (const int level)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    T8_ASSERT (level >= 0);
also check that level is smaller than maxlvl.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        coords[i] = coords_int[i] / (double) t8_standalone_scheme<TEclass>::get_root_len ();
```suggestion
        coords[i] = (double) coords_int[i] / t8_standalone_scheme<TEclass>::get_root_len ();
```
Please double check this befor adding. But I think dividing and int by a double results into a double (again: not 100% sure, but please look it up). 

also use a more descriptive name than "i".

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    t8_element_coord h
```suggestion
    t8_element_coord length
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        current_out_coords[dim] = ((t8_standalone_element<TEclass> *) elem)->coords[dim] + current_ref_coords[dim] * h;
```suggestion
        current_out_coords[dim] = ((t8_standalone_element<TEclass> *) elem)->coords[dim] + current_ref_coords[dim] * length;
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_new (int length, t8_element_t **elem) const
```suggestion
  element_new (const int length, t8_element_t **elem) const
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      }
```suggestion
      for (int ielem = 0; ielem < length; ielem++) {
        t8_standalone_scheme<TEclass>::element_init (1, elem[ielem]);
      }
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
```suggestion
    t8_standalone_element<TEclass> *el = (t8_standalone_element<TEclass> *) elem;
    /* Set all values to 0 */
    for (int ielem = 0; ielem < length; ielem++) {
      t8_standalone_scheme<TEclass>::element_set_linear_id ((t8_element_t *) (el + ielem), 0, 0);
      T8_ASSERT (t8_standalone_scheme<TEclass>::element_is_valid ((t8_element_t *) (el + ielem)));
    }
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_init (int length, t8_element_t *elem)
```suggestion
  element_init (const int length, t8_element_t *const elem)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   *                       were created by \ref t8_element_new should never occur.
```suggestion
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   *                       were created by \ref t8_element_new should never occur.
please update this comment in general.

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      }
or call element_init (length, elem) instead??

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_deinit (int length, t8_element_t *elem)
```suggestion
  element_deinit (const int length, t8_element_t *elem)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_deinit (int length, t8_element_t *elem)
why is this function not implemented?

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_destroy (int length, t8_element_t **elem) const
```suggestion
  element_destroy (const int length, t8_element_t **elem) const
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    int is_valid;
```suggestion
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    is_valid = 0 <= el->level && el->level <= T8_ELEMENT_MAXLEVEL[TEclass];
```suggestion
    int is_valid = 0 <= el->level && el->level <= T8_ELEMENT_MAXLEVEL[TEclass];
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_MPI_Pack (t8_element_t **const elements, const unsigned int count, void *send_buffer, int buffer_size,
```suggestion
  element_MPI_Pack (t8_element_t **const elements, const unsigned int count, void *send_buffer, const int buffer_size,
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_get_len (t8_element_level level)
```suggestion
  element_get_len (const t8_element_level level)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  compute_cubeid (const t8_standalone_element<TEclass> *elem, int level)
```suggestion
  compute_cubeid (const t8_standalone_element<TEclass> *elem, const int level)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
```suggestion
    if (elem->level == level) {
      return;
    }
    if (elem != ancestor) {
      t8_standalone_scheme<TEclass>::element_copy ((const t8_element_t *) elem, (t8_element_t *) ancestor);
    }
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    int num_zeros = t8_standalone_scheme<TEclass>::number_of_leading_zeros (maxexclor);
```suggestion
    const int num_zeros = t8_standalone_scheme<TEclass>::number_of_leading_zeros (maxexclor);
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    return level;
```suggestion
    return SC_MIN (num_zeros, (int) SC_MIN (elem1->level, elem2->level));
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  number_of_leading_zeros (t8_element_coord maxexclor)
```suggestion
  number_of_leading_zeros (const t8_element_coord maxexclor)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    return num_zeros;
```suggestion
    const int num_of_active_bits_used = SC_LOG2_32 (maxexclor) + 1;
    T8_ASSERT (num_of_active_bits_used <= T8_ELEMENT_MAXLEVEL[TEclass]);

    return T8_ELEMENT_MAXLEVEL[TEclass] - num_of_active_bits_used;
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
please use a better variable name than "i"

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
Please use a better variable name than "i"

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
Please use a better variable name than "i"

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +                        const t8_element_coord length, t8_cube_id cube_id)
```suggestion
                        const t8_element_coord length, const t8_cube_id cube_id)
```

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  }
can this be a constexpr?

2025-01-17 11:29 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  num_descendants_at_leveldiff (const t8_element_t *elem, const int leveldiff)
if we make leveldiff an unsigend int we could remove the first if and make it a constexpr.

2025-01-17 12:09 UTC, Davknapp commented
Had a look at the other files, liked them. If you address my comments we are ready to merge!

2025-01-17 13:16 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    return T8_ELEMENT_NUM_CORNERS[TEclass];
We did not include the Pyramid-specific code, since the Pyramids aren't a part of the scheme yet.

2025-01-17 13:19 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    ToDo-Type */
This is a reminder, that we made all type functions a comment and that this needs to be adressed when introduce types.

2025-01-17 14:45 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_set_linear_id (t8_element_t *elem, int level, t8_linearidx_t id)
The id is overwritten in the function and therfore can't be const.

2025-01-20 10:19 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      }
The element_init call might not be possible if the elements returned from the mempool are not consecutive.

2025-01-20 11:56 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  get_root (t8_element_t *elem)
We can't const the element here since it's also the output.

2025-01-20 11:57 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    t8_standalone_element<TEclass> *el = (t8_standalone_element<TEclass> *) elem;
We can't const the element here since it's also the output.

2025-01-20 11:59 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_get_num_siblings (const t8_element_t *elem)
The function will be extended in the future with types, therefore we used this structure. But I changed it a bit to make the future change clear.

2025-01-20 12:01 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
The current structure is a preparation for a future addition of types.

2025-01-20 12:02 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    const int num_children = t8_standalone_scheme<TEclass>::element_get_num_children ((const t8_element_t *) el);
Yes, we changed that but in a different way

2025-01-20 12:02 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    return child_id;
The current structure is a preparation for a future addition of types.

2025-01-20 12:04 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    int real_level = cube_ancestor_level;
The structure occurred because we left the types code out: But we made it clear now.

2025-01-20 12:06 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +                          int is_smaller_face)
Both elements are face elements and we explicitly want that they can be the same (overridden)  Therefore it's better to keep it this way and just const the ints.

2025-01-20 12:12 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +      while (true) {
Yes, changed it up

2025-01-20 12:18 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    }
The ancestor could be empty, if the element level is the level, so we can't switch that.

2025-01-20 12:25 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +        coords[i] = coords_int[i] / (double) t8_standalone_scheme<TEclass>::get_root_len ();
Just had another look at it. It shouldn't matter where you put the cast to a double. As long as one of the numbers is a double you will use the / operator of a double.

2025-01-20 15:43 UTC, ole-alb commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
1. Yes we did that
2. Since we will implement the face functions very soon we decided to not implement the is_valid assertion already.

2025-01-20 15:57 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  }
I think we could remove `element_size` from the class and replace it here by `sizeof (t8_standalone_element<TEclass>)`
Then we can make this function static as well

2025-01-20 15:59 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_deinit (int length, t8_element_t *elem)
Because nothing is allocated in elements in this scheme, so nothing needs to be deallocated

2025-01-20 16:03 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   *                       were created by \ref t8_element_new should never occur.
`called_new` is no longer part of the interface, but the comment was not updated in all of the default files as well and should be updated here

2025-01-21 08:11 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  }
I like this idea, too.

2025-01-21 08:37 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_elements.hxx
> +                                             [T8_ELEMENT_DIM[TEclass]];
Could be removed for this PR
```suggestion
```

2025-01-21 08:50 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  }
```suggestion
    if (level != 0) {
      for (int i = 0; i < T8_ELEMENT_DIM[TEclass]; i++) {
        cube_id |= ((elem->coords[i] & h) ? 1 << i : 0);
        }
      }
    return cube_id;
  }
```
might allow this function to be constexpr

2025-01-21 08:54 UTC, lukasdreyer commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +    const int num_of_active_bits_used = SC_LOG2_32 (maxexclor) + 1;
rename maxexclor to something more generic, as this function does not care about where the input comes from.

2025-01-24 08:35 UTC, Davknapp requested changes

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr size_t
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr t8_element_shape_t
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  element_get_face_shape (const t8_element_t *elem, const int face) noexcept
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr void
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr t8_element_coord
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr t8_cube_id
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr int
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  number_of_leading_zeros (const t8_element_coord coordinates) noexcept
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  get_root_len () noexcept
please document this function

2025-01-24 08:35 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  static constexpr t8_linearidx_t
please document this function

2025-01-27 08:32 UTC, Davknapp requested changes

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  /** The length of a element at a given level in integer coordinates */
input and output of this function is not documented.

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  * \param[in] level
please document the return, too.

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   * \param[in] elem2      Second input element
please document the return of the function, too.

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   * \param[in] coordinates      Input coordinates
please document the return of the function too.

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +  /** Compute the length of the root element of the current TEclass. The length for a Vertex root element is always 0. */
please document the return value too.

2025-01-27 08:32 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   * \param[in] leveldiff Difference between the level of the element
please docuemnt the return value too.

2025-01-27 09:37 UTC, Davknapp submitted a review, later dismissed

2025-01-27 09:42 UTC, Davknapp commented on src/t8_schemes/t8_standalone/t8_standalone_implementation.hxx
> +   *                       were created by \ref t8_element_new should never occur.
In the documentation you still reference to called_new, Please update the documentation.

2025-01-27 10:31 UTC, Davknapp approved these changes

2025-01-27 10:49 UTC, merged