Feature use splittedvtkfunction
DLR-AMR/t8code pull request #180
Opened 2022-02-21 13:02 UTC by Veli-hub

**_Describe your changes here:_**
Describe your changes here:
With this pull request, we want to merge the new separated approach of writing a vtk file for a forest. We have two dedicated functions, the first builds the vtkUnstructuredGrid object and the other writes the vtu file. This separated approach is implemented to aid in the Catalyst project and could be useful for cases when we do not want to write the file everytime when building the grid.

src/Makefile.am added src/t8_forest_catalyst.hpp and cxx
src/t8_forest_catalyst.hxx and cxx contain the new separated functions
included <t8_schemes/t8_default/t8_default_... files to src/t8_forest/t8_forest_vtk.cxx Note: Was this necessary? Need to check that.

Question to reviewers: Wollen wir T8_EXTERN_C_BEGIN () in der t8_forest_catalyst.cxx verwenden bzw generell? Ist bisher auskommentiert. 

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

2022-04-11 14:58 UTC, Davknapp requested changes
All in all it looks good to me. 
The catalyst-files are currently under the src-directory, yet they provide functions for the forest. Is there a reason, why they are not under src/t8_forest? If no, please move them there.

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +/* We have to free the allocated memory for the cellTypes Array and the other arrays we allocated memory for. */
```suggestion
```
No array was allocated, and the smartPointer don't need an explicit delete

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> + * Since we want to write multiple files, the processes
I think it would be better to move this comment in the `#if T8_ENABLE_MPI` part

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> + */
Where does this happen, or can this comment be deleted?

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +/* *INDENT-OFF* */
Why is the indenting disabled for the whole function?

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +   * beforehand how many entries the array needs.
I think the code concerning this comment is deleted or elsewhere. Move or delete this comment.

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +   * We have to define the vtkTypeInt64Array that hold
```suggestion
   * We have to define the t8_vtk_gloidx_array_type_t that hold 
```

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> + * We want to write num_data many timesteps/arrays.
```suggestion
 * We want to write num_data many arrays.
```
The data can be arbitrary

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +      vtkSmartPointer < vtkCell > pvtkCell = NULL;
You construct a smart pointer for every element in this loop. Couldn't you move this line outside the loop and reuse this pointer for every element?

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +      t8_element_t       *element =
Move the declaration of *element outside of the loops.

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +
```suggestion
```

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +
```suggestion
```

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +  t8_vtk_gloidx_array_type_t *vtk_treeid = t8_vtk_gloidx_array_type_t::New ();
Each array should only be constructed if it is needed

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +                  /* Write the user defined data fields.
Indent this comment correctly

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +                  /* We have to free the allocated memory for the cellTypes Array and the other arrays we allocated memory for. */
Indent this comment correctly

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.cxx
> +                  /* Return whether writing was successful */
Indent this comment correctly

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.hxx
> +int
Indent this file correctly

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_catalyst.hxx
> +#if T8_WITH_VTK
Move the above comment also into the `#if T8_WITH_VTK`-part

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_vtk.h
> +void
Fix this indentation

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest_vtk.h
> +
```suggestion
```

2022-04-11 14:58 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
> -static void
This function is independant of the linking with vtk. Therefore, we can delete the makros, I think.

2022-10-24 14:27 UTC, Davknapp requested changes
Currently there is a lot of code-duplication in t8_forest_vtk and t8_forest_catalyst, which should be avoided. t8_forest_vtk should call the function to translate the forest into a vtkUnstructuredGrid and then use the vtkwriter.

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
> +  t8_element_t        element;
When you move the `element` inside of the for-loop that iterates over all elements you can make it const.

2022-10-24 14:27 UTC, Davknapp commented on example/geometry/Makefile.am
> -	example/geometry/t8_occ_naca
This example should not be removed.

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
>  t8_curved_element_get_reference_node_coords (const t8_element_t *elem,
Change the functions in the header, too.

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
> +t8_forest_vtk_write_file_via_API (const t8_forest_t forest,
See comment above.

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
>        t8_element_shape_t  element_shape = scheme->t8_element_shape (element);
The shape can be const

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
> +      num_corners = t8_get_number_of_vtk_nodes (element_shape, curved_flag);
This can be made const, too.

2022-10-24 14:27 UTC, Davknapp commented on src/t8_forest/t8_forest_vtk.cxx
> +      for (t8_locidx_t ivertex = 0; ivertex < num_corners;
num_node is an int, therefore ivertex should be an int too

2023-03-28 06:44 UTC, chiaraMaHe commented
Close Pull-request and re-open for the new branch/rework the branch

2025-02-17 15:27 UTC, closed without merging