t8_test_shmem to t8_gtest_shmem
DLR-AMR/t8code pull request #393
Opened 2022-12-23 12:04 UTC by WeberJulia

**_Describe your changes here:_**

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] New tests use the Google Test framework
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

2023-01-16 15:34 UTC, jmark requested changes
This section shows you how to add custom error messages to you assertions:
https://google.github.io/googletest/primer.html#assertions

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +  EXPECT_TRUE(internode != sc_MPI_COMM_NULL);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +  EXPECT_TRUE(intranode == sc_MPI_COMM_NULL);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +  EXPECT_TRUE(internode == sc_MPI_COMM_NULL);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_EQ(shmem_type, control_shmem_type);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_EQ(comm, check_comm);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_TRUE(check_count == array_length);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_TRUE(check_size == element_size);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +      EXPECT_TRUE(0 < array_length / 3
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +      EXPECT_TRUE(value == i);
Please transfer custom error message.

2023-01-16 15:34 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_TRUE(t8_shmem_array_is_equal (copy_array, shmem_array));
Please transfer custom error message.

2023-01-30 12:53 UTC, WeberJulia commented
compare PR #421

2023-01-30 12:53 UTC, closed without merging