Test shmem
DLR-AMR/t8code pull request #421
Opened 2023-01-30 12:32 UTC by WeberJulia

**_Describe your changes here:_**

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] New tests use the Google Test framework
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

2023-01-30 12:51 UTC, WeberJulia commented
compare PR #393

2023-02-06 16:00 UTC, jmark requested changes

2023-02-16 15:00 UTC, jmark requested changes
I highly recommend to alwasy use assertions when converting any `SC_CHECK_ABORT` calls. That way the test stops early when there are problems. Otherwise we risk segfaults or other nasty errors.

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> -    t8_productionf ("Checking shared memory type %s.\n",
Please convert to `t8_debugf`.

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> -    t8_productionf ("Checking shared memory type %s.\n",
If you have a different opinion about this you can answer to my comment and explain. :)

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_EQ(shmem_type, control_shmem_type) << "Setting shmem type not succesfull.";
Should be an assertion.

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +        EXPECT_EQ(intrarank, 0);
Make it an assertion and please add the message..

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> +    EXPECT_EQ(shared_int[0], random_number);
Make it an assertion and please add the message..

2023-02-16 15:00 UTC, jmark commented on test/t8_data/t8_gtest_shmem.cxx
> -      t8_productionf ("I have write permissions\n");
Conver to `t8_debug_f`.

2023-03-13 14:19 UTC, jmark requested changes
There is still a change request left. Maybe you forgot it?

2023-03-14 14:16 UTC, jmark approved these changes

2023-03-14 14:18 UTC, merged