Fix issue 399 - Remove processing of linear geometries for speedup
DLR-AMR/t8code pull request #501
Opened 2023-04-03 07:47 UTC by jfussbro

**_Describe your changes here:_**

Before this PR all geometries were linked to occ geometries (when using curved option) even if they are linear.
This PR skips linear geometries when linking to occ geometries, resulting in a slightly better performance. There is now the posibility to use curved meshes in the time_forest_partition script.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] New tests use the Google Test framework
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

2023-04-05 08:36 UTC, sandro-elsweijer requested changes

2023-04-05 08:36 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +    // partition = 1;
Please remove this code fragment

2023-04-05 08:36 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +      t8_global_productionf("There will be no partition of the mesh due to the use of the curved mesh option. "
```suggestion
      t8_global_productionf("The cmesh is not partitioned due to the usage of the curved mesh option. "
```

2023-04-05 08:36 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +      partition = 0;
```suggestion
      partition = 1;
```

2023-04-05 08:36 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +    }
This bit of code is only executed, when no `msh` file is specified, and we only support curved geometries for `msh` files. Therefore, this change here is not necessary. But we should abort, if the user uses the `use_occ` option but does not provide an `msh` file along with it

2023-04-05 08:36 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +                         "If used, meshes will be curved to original geometries (msh- and brep-files nessesary).");
```suggestion
                         "If used, meshes will be curved to original geometries (msh- and brep-files necessary).");
```

2023-04-05 08:36 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_readmshfile.cxx
> +              if (occ_geometry->t8_geom_is_plane(edge_geometry_tag))
```suggestion
              if (occ_geometry->t8_geom_is_line(edge_geometry_tag))
```

2023-04-05 08:36 UTC, sandro-elsweijer commented on src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
> +   * \return                     0 if edge is line.
```suggestion
   * \return                     1 if edge is line.
```

2023-04-05 08:36 UTC, sandro-elsweijer commented on src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
> +   * \return                     0 if face is plane.
```suggestion
   * \return                     1 if face is plane.
```

2023-04-18 10:41 UTC, sandro-elsweijer requested changes
I have one last request and then we can merge

2023-04-18 10:41 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +    /* Abort if use_occ option selected but no msh file provided */
This check should be placed [here](https://github.com/DLR-AMR/t8code/blob/3f73e1715f9a3c76ed7a8c03f0e00a14bdcfb846/benchmarks/time_forest_partition.cxx#L469-L477). The checks for wron user input are always handled directly after the parsing of the CLI options.

2023-04-19 08:28 UTC, sandro-elsweijer requested changes

2023-04-19 08:28 UTC, sandro-elsweijer commented on benchmarks/time_forest_partition.cxx
> +          && (test_linear_cylinder || test_occ_cylinder || test_tet || use_occ))) {
This change results in not being able to specify a `msh` file and using the `use_occ` option at the same time. The program is only executed, if the `if` statement is false

2023-07-04 08:09 UTC, chiaraMaHe approved these changes

2023-07-04 19:40 UTC, sandro-elsweijer commented
I am afraid the reformatting deleted all the changes you made @jfussbro. So the skipping of linear geometries is completely missing now.

2023-07-26 13:24 UTC, sandro-elsweijer approved these changes

2023-07-26 13:24 UTC, merged