fix some typos
DLR-AMR/t8code pull request #642
Opened 2023-07-21 10:06 UTC by ranocha

**_Describe your changes here:_**

I ran a GitHub action checking for common typos locally and fixed a few. I also included the GitHub action workflow and a corresponding configuration file here. Currently, it is configured to exclude some typos that appeared systematically in the code, e.g.,

- boundery instead of boundary in `t8_forest_partition_test_boundery_element`
- consistend instead of consistent in `t8_cmesh_trees_is_face_consistend`
- hashs instead of hashes in `num_hashs`
- tpye instead of type in `T8_DPYRAMID_ROOT_TPYE`
- elemets instead of elements in `MAX_NUM_ELEMETS`

I wasn't sure whether fixing these typos would be a breaking change so I didn't touch them.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] New Datatypes are added to t8indent_custom_datatypes.txt
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2023-07-21 10:37 UTC, sandro-elsweijer commented
Hello @ranocha,
thank you very much for your contributions!
I will take a look at the changes and also take a look, if we should keep the exceptions, or if it's the right time to rename these functions.
It is great that you already added a BSD file, but could you please add a valid e-mail address as well?
Furthermore, we use some indent scripts for our code located here: `scripts/`. Can you please indent your changed files, so that the CI checking the indentation runs through?

2023-07-21 10:45 UTC, ranocha commented
```bash
$ ls scripts/
check_if_all_files_indented.scp  pre-commit                                       su2_mesh_to_gmsh.py
check_if_file_indented.scp       README.md                                        t8indent
create_todo_list.sh              remove-all-if-zero-pragmas.sh                    t8indent_custom_datatypes.txt
find_all_source_files.scp        remove-all-windows-cariage-return-characters.sh
indent_all_files.scp             remove_double_const.scp

$ scripts/indent_all_files.scp
# runs

$ git status
On branch hr/typos
Your branch is up to date with 'myfork/hr/typos'.

nothing to commit, working tree clean
```

Which script do I need to run to indent the files correctly?

2023-07-21 10:54 UTC, sandro-elsweijer commented
You used the script in the exact right way, but our indent scripts sometimes have problems with cpp code and do confusing things. We want to switch to clang-format in the long run. But for now, we have to stick with it.
Almost all of our CI scripts upload artifacts if they fail, and the indentation check does that too. If you open the failed workflow run and click on `Summary` at the top left, you can download the artifact which mentions the file names and wrongly indented lines. Using `./scripts/t8indent <path/to/unindented/file>` you should be able to indent it correctly. 
You can also attach a git commit hook, which checks all files marked for the next commit when you run `git commit` as described here: https://github.com/DLR-AMR/t8code/wiki/Coding-Guideline#indentation

2023-07-21 11:17 UTC, sandro-elsweijer requested changes
This is only a partial review, I am going to make a coffee for the rest.
@ranocha, do you know why the spell checker wants to replace `occured` with `diagonal`?

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/IO/cmesh/gmsh/t8_read_msh_file.cxx
> +    t8_global_productionf ("An error diagonal while reading %s.msh file.\n",
```suggestion
    t8_global_productionf ("An error occurred while reading %s.msh file.\n",
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/IO/cmesh/tetgen/t8_forest_from_tetgen.cxx
> +    t8_debugf ("An error diagonal while reading %s files.\n", prefix);
```suggestion
    t8_debugf ("An error occurred while reading %s files.\n", prefix);
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/IO/cmesh/tetgen/t8_read_tetgen_file.cxx
> +    t8_debugf ("An error diagonal while reading %s files.\n", prefix);
```suggestion
    t8_debugf ("An error occurred while reading %s files.\n", prefix);
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/IO/cmesh/tetgen/t8_time_tetgen_file.cxx
> +    t8_debugf ("An error diagonal while reading %s files.\n", prefix);
```suggestion
    t8_debugf ("An error occurred while reading %s files.\n", prefix);
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/IO/cmesh/triangle/t8_read_triangle_file.cxx
> +    t8_debugf ("An error diagonal while reading %s files.\n", prefix);
```suggestion
    t8_debugf ("An error occurred while reading %s files.\n", prefix);
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on example/cmesh/t8_cmesh_hypercube_pad.cxx
> +  /* Pad hypercube with given element class. */
```suggestion
  /* Add hypercube with given element class. */
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on scripts/su2_mesh_to_gmsh.py
> +    print 'An IO-error diagonal.\n\t', error
```suggestion
    print 'An IO-error occurred.\n\t', error
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on src/t8_element_c_interface.h
> + * \param [in,out] elem2 On return the face  \a elem1 with respective
```suggestion
 * \param [in,out] elem2 On return the face element \a elem1 with respect
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on src/t8_element_cxx.hxx
> +   *  \param [in,out] elem2 On return the face  \a elem1 with respective
```suggestion
   *  \param [in,out] elem2 On return the face element  \a elem1 with respect
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on src/t8_forest/t8_forest_adapt.cxx
> +     * even if you do not want this output. It fixes a bug that diagonal on JUQUEEN, where the
```suggestion
     * even if you do not want this output. It fixes a bug that occurred on JUQUEEN, where the
```

2023-07-21 11:17 UTC, sandro-elsweijer commented on src/t8_forest/t8_forest_adapt.cxx
> +     * even if you do not want this output. It fixes a bug that diagonal on JUQUEEN, where the
```suggestion
     * even if you do not want this output. It fixes a bug that occurred on JUQUEEN, where the
```

2023-07-21 12:03 UTC, sandro-elsweijer requested changes
We discussed the spell checking exceptions you added to the spell checker and decided, that we will make a new release shortly after merging this PR. Therefore, it would be nice if you could remove the exceptions and run the spell checking again :)

2023-07-21 12:03 UTC, sandro-elsweijer commented on tutorials/general/t8_step5_element_data.cxx
> +  /* Copy the 's volumes from our data array to the output array. */
```suggestion
  /* Copy the element's volumes from our data array to the output array. */
```

2023-07-21 12:03 UTC, sandro-elsweijer commented on tutorials/general/t8_step5_element_data_c_interface.c
> +  /* Copy the 's volumes from our data array to the output array. */
```suggestion
  /* Copy the element's volumes from our data array to the output array. */
```

2023-07-21 12:03 UTC, sandro-elsweijer commented on tutorials/general/t8_step6_stencil.cxx
> +  /* Copy the 's volumes from our data array to the output array. */
```suggestion
  /* Copy the element's volumes from our data array to the output array. */
```

2023-07-21 12:03 UTC, sandro-elsweijer commented on tutorials/general/t8_step7_interpolation.cxx
> +  /* Copy the 's data from the data array to the output array. */
```suggestion
  /* Copy the element's data from the data array to the output array. */
```

2023-07-21 12:17 UTC, sandro-elsweijer commented
A quick question about the spell checker: Since the newly implemented workflow did not run yet, I suppose you ran the spell check locally? Which commands did you use for that?

2023-07-22 10:04 UTC, ranocha commented
Thanks for the quick review! I applied your suggestions.

> @ranocha, do you know why the spell checker wants to replace `occured` with `diagonal`?

Maybe a copy-pasta error?

2023-07-25 15:06 UTC, ranocha commented
> A quick question about the spell checker: Since the newly implemented workflow did not run yet, I suppose you ran the spell check locally? Which commands did you use for that?

`typos`. See https://github.com/crate-ci/typos#install

2023-07-26 08:32 UTC, sandro-elsweijer approved these changes

2023-07-26 08:56 UTC, ranocha commented
Thanks for your review and the fixes!

2023-07-26 10:45 UTC, merged