Feature curved tetrahedron
DLR-AMR/t8code pull request #742
Opened 2023-09-12 09:21 UTC by jfussbro

**_Describe your changes here:_**

Enables usability of curved tetrahedral elements

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2023-09-13 15:29 UTC, sandro-elsweijer requested changes
Here are some first comments :)

2023-09-20 10:08 UTC, jmark requested changes
Nice work! I like your code. It is well commented and clean & lean.

As discussed, please also add triangle/tetraeder support for the Curved Mesh Tutorial.

2023-09-20 10:08 UTC, jmark commented on src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.hxx
> +   * \param [in]  ref_coords  Array of 3 entries, specifying a point in [0,1]^3.
```suggestion
   * \param [in]  ref_coords  Array of \a dimension x \a num_coords many entries, specifying points in \f$ [0,1]^\mathrm{dim} \f$.
   * \param [in]  num_coords  The number of points to map.
```

2023-09-20 10:08 UTC, jmark commented on src/t8_geometry/t8_geometry_implementations/t8_geometry_occ.cxx
> +    t8_geometry_occ::t8_geom_evaluate_occ_tet (cmesh, gtreeid, ref_coords, out_coords);
```suggestion
    t8_geometry_occ::t8_geom_evaluate_occ_tet (cmesh, gtreeid, ref_coords, 1, out_coords);
```
See comments below.

2023-09-25 12:14 UTC, jmark requested changes

2023-09-25 14:46 UTC, jmark approved these changes

2023-09-27 13:17 UTC, jmark commented
LGTM! @sandro-elsweijer If you agree we can merge.

2023-10-02 14:22 UTC, sandro-elsweijer commented
I think it would be best to wait for this, till the evaluations are completed. The usage of the advection solver is good for testing the code and some bugs could become observable :)

2023-11-29 20:58 UTC, jmark commented
@jfussbro @sandro-elsweijer 

I encountered a strange phenomenon when I computed interpolation nodes with curved triangles. I present you a (minimal) working example via a curved mesh around a cylinder. The respective files to reproduce the results are attached to this comment. 

But first let me show what the problem is:
![grafik](https://github.com/DLR-AMR/t8code/assets/10619309/f5715ac5-c1bc-4caf-bd58-f3803fe17309)
This is a scatter plots of interpolation nodes computed via the Julia interface T8code.jl which in turn is linked against the t8code library with the curved tri/tets merged in. I shifted one curved triangle into empty space on purpose to better show the details. The colors of each point represent the Jacobians at this point in space computed with the polynomial spanned by the interpolation nodes. Clearly the curved elements have some troubles. Even intersecting into neighboring elements. The refinement level is set to 0 in this case.

I did the same with a C++ version (attached to this comment) and got the same strange behavior:
![grafik](https://github.com/DLR-AMR/t8code/assets/10619309/796a892e-894a-4005-b7d1-07b295893cf0)

To reproduce this please consider these files:
[t8_features_curved_triangles_generate_cmesh_cylinder_2d.geo.txt](https://github.com/DLR-AMR/t8code/files/13505378/t8_features_curved_triangles_generate_cmesh_cylinder_2d.geo.txt)
[scatter_plot.cxx.txt](https://github.com/DLR-AMR/t8code/files/13505379/scatter_plot.cxx.txt)
[scatter_plot.gpi.txt](https://github.com/DLR-AMR/t8code/files/13505380/scatter_plot.gpi.txt)

**Note above C++ file is linked against t8code with curved tri/tets feature which in turn was merged with the current main. There was a change in the reference basis vectors for tris/tets which is not merged in this PR yet. The same erraneous behavior is observed with the old reference basis, too.**

2024-03-12 13:01 UTC, sandro-elsweijer requested changes

2024-03-20 09:17 UTC, sandro-elsweijer commented on src/t8_geometry/t8_geometry_helpers.c
> +}
Newline at EOF is missing

2024-03-20 14:05 UTC, jfussbro commented on src/t8_geometry/t8_geometry_helpers.c
> +}
The new line is deleted by the indention script. But right now there is one black line at the EOF. Isn't that enough?

2024-03-21 10:04 UTC, sandro-elsweijer approved these changes

2024-03-21 10:05 UTC, merged