Add cmesh example cubed spherical shell  [3/n].
DLR-AMR/t8code pull request #788
Opened 2023-10-09 15:44 UTC by jmark

**_Describe your changes here:_**

This is a follow-PR to https://github.com/DLR-AMR/t8code/pull/787.

![grafik](https://github.com/DLR-AMR/t8code/assets/10619309/82a8993a-31eb-4fde-b186-928d54daea7d)

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-01-11 17:14 UTC, jmark commented
@sandro-elsweijer I assigned you this PR since it is nearly identical to https://github.com/DLR-AMR/t8code/pull/787 and should not add much workload to review it.

2024-01-18 12:09 UTC, sandro-elsweijer requested changes
I would find it better to adapt the `t8_cmesh_new_quadrangulated_spherical_surface` routine from your previous PR. We could add a 2D/3D flag and then just add another loop for the radial layers.
The approach to make an independent forest seems to be overkill and would involve more code maintenance in the future

2024-01-22 17:21 UTC, jmark commented on src/t8_cmesh/t8_cmesh_examples.c
> +  const int two_to_nl = num_levels > 0 ? 1 << num_levels : 1; /* 2^num_levels */
Actually, you are rigtht! Fixed!

2024-01-22 17:24 UTC, jmark commented on example/cmesh/t8_cmesh_geometry_examples.cxx
> +    t8_cmesh_t cmesh = t8_cmesh_new_cubed_spherical_shell (inner_radius, shell_thickness, num_levels, num_layers, comm);
Do we really want to rename this? "Cubed sphere" is actually an established term.

2024-01-22 17:27 UTC, jmark commented on src/t8.h
> +/** Cube squared. */
Maybe. Removed it.

2024-01-25 14:34 UTC, sandro-elsweijer approved these changes

2024-01-25 15:46 UTC, merged