Rename element ref coords integer coords
DLR-AMR/t8code pull request #832
Opened 2023-11-09 14:41 UTC by sandro-elsweijer

**_Describe your changes here:_**
I was heavily confused by the current naming of the element reference coords functions, so I renamed the integer versions

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2023-11-10 13:58 UTC, lukasdreyer commented
This function is not actually part of the c interface, and I would argue that it should not be, since it assumes that the SFC internally uses integer coordinates on `[0, 2^l)`, which the SFC does not need to do. The internal counterpart can be used for the version that is scaled to [0,1], but should not be accessible from the outside

2024-01-30 15:27 UTC, lukasdreyer commented
@holke: I had a discussion offline with @sandro-elsweijer about the necessity of this functionality in the interface, and he mentioned that you had some arguments why it should not be removed. Could you elaborate on that?
In my opinion, this functionality as well as the `anchor` functionality are implementation details, if the user wants to access geometry information of an element, they should use `t8_element_reference_coords` or `t8_element_vertex_reference_coords`

2024-04-08 07:56 UTC, Niklas997 requested changes
The pull request looks good! Please merge the current main branch and resolve the conflicts. Afterwards, we are able to merge it.

2024-04-08 07:56 UTC, Niklas997 commented on src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
>    int len;
```suggestion
```

2024-04-08 07:56 UTC, Niklas997 commented on src/t8_schemes/t8_default/t8_default_quad/t8_default_quad_cxx.cxx
> +  len = P4EST_QUADRANT_LEN (elem->level);
```suggestion
  const int len = P4EST_QUADRANT_LEN (elem->level);
```

2024-04-08 07:56 UTC, Niklas997 commented on src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
>    int len;
```suggestion
```

2024-04-08 07:56 UTC, Niklas997 commented on src/t8_schemes/t8_default/t8_default_hex/t8_default_hex_cxx.cxx
> +  len = P8EST_QUADRANT_LEN (elem->level);
```suggestion
  const int len = P8EST_QUADRANT_LEN (elem->level);
```

2024-04-08 13:05 UTC, Niklas997 approved these changes

2024-04-08 13:06 UTC, merged