Rework linear geometry test
DLR-AMR/t8code pull request #912
Opened 2024-01-31 09:42 UTC by sandro-elsweijer

**_Describe your changes here:_**
Move linear geometry test to a separate file to keep structure from src directory.
Moreover, adapt the linear geometry test so that it tests all element shapes.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [ ] The author added a BSD statement to `doc/` (or already has one)

2024-02-02 12:13 UTC, jmark requested changes
LGTM! Just a minor suggestion.

2024-02-02 12:13 UTC, jmark commented on test/t8_geometry/t8_geometry_implementations/t8_gtest_geometry_linear.cxx
> +t8_cmesh_t
```suggestion
static t8_cmesh_t
```

2024-02-05 16:30 UTC, jmark commented
@sandro-elsweijer Please merge in the latest `main`.

2024-02-05 16:30 UTC, jmark approved these changes

2024-03-08 10:32 UTC, closed without merging

2024-03-08 10:32 UTC, sandro-elsweijer commented
The changes were already introduced with the new geometry handler https://github.com/DLR-AMR/t8code/pull/950