Feature cmesh vertex connectivity
DLR-AMR/t8code pull request #960
Opened 2024-02-27 19:00 UTC by holke

**_Describe your changes here:_**

Implemented two classes for cmesh global vertex id handling.

tree to vertex - Each local tree and ghost stores the list of global ids of its vertices.
vertex to tree - Each global vertex stores a list of all local trees and ghost trees and vertices that share this global vertex.

We implemented setter and getter functions and tests.

This feature is still in development.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

As a reviewer please read through all the code lines and make sure that the code is fully understood, bug free, well-documented and well-structured.

#### General
- [ ] The reviewer executed the new code features at least once and checked the results manually

- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)

#### Tests
- [ ] The code is covered in an existing or new test case using Google Test

#### Github action

- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)
- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)

  If the Pull request introduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

#### Scripts and Wiki

- [ ] If a new directory with source-files is added, it must be covered by the `script/find_all_source_files.scp` to check the indentation of these files.
- [ ] If this PR introduces a new feature, it must be covered in an example/tutorial and a Wiki article.

#### Licence

- [x] The author added a BSD statement to `doc/` (or already has one)

2024-02-29 13:26 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +  /* Now sort the list and add the global indices of each tree. */
We do not sort the unorderd_map entries but the list stored in each entry.
This is required when we need the array of global indices of a single ttre, for example when building the vtt structure from it.

2024-02-29 13:27 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +  /* Call standard constructor */
To call any necessary init routines.
Currently there is not much, but it is future proof if the standard constructor gets more involved later.

2024-02-29 13:28 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +   * exists exactly once in the list.
i will have another look at it

2024-03-04 07:26 UTC, chiaraMaHe commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +  /* Call standard constructor */
Is it enough to just call the constructor? Dont we have to save the object?

2024-03-04 07:27 UTC, chiaraMaHe commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +   * exists exactly once in the list.
Me too

2025-01-15 10:07 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers

```

2025-01-15 10:08 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.cxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-15 10:08 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.h
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-15 10:08 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-15 10:08 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-15 10:08 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-15 10:09 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_vertex_to_tree.cxx
> +  Copyright (C) 2015 the developers
```suggestion
  Copyright (C) 2024 the developers
```

2025-01-30 11:53 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +   * Note that this is very memory intensive, doubling the required memory. */
```suggestion
   * Note, that this is very memory intensive, doubling the required memory. */
```

2025-01-30 12:57 UTC, sandro-elsweijer reviewed
partial review

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +      global_ids_per_tree[tree_index].push_back (new_pair);
Do we really need a pair here?
Instead of saving the global and local index in a random order, we could also save them in the order of the local indices.
Something like 
```suggestion
      /* If vector is empty fill it with as many values as the tree has vertices. */
      if (global_ids_per_tree[tree_index].size() == 0) vec.resize(t8_eclass_num_vertices(tree_class), -1);
      global_ids_per_tree[tree_index][vertex_index] = global_index;
```

the vector would the be of the type `std::vector<std::vector<t8_gloidx_t>>`

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +  /* Now sort the list and add the global indices of each tree. */
With my proposed solution from above we would also not need to sort, since we save the indices in a already sorted manner

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +      itree, tree_indices.size (), num_tree_vertices);
It would then also shorten this to:
```suggestion
#if T8_ENABLE_DEBUG
    /* Check if no -1 is remaining in the nodes. If one is remaining, this node could not be mapped. */
    auto faulty_index = std::find(tree_indices.begin(), tree_indices.end(), -1);
    SC_CHECK_ABORTF (tree_indices.end() != faulty_index ,
      "ERROR. Node %i of tree %i could not be mapped to its global index.\n",
      std::distance(tree_indices.begin(), faulty_index), itree);
#endif /* T8_ENABLE_DEBUG */
```

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +    T8_FREE (global_tree_indices);
And this to
```suggestion
    const t8_gloidx_t global_tree_id = t8_cmesh_get_global_id (cmesh_from, itree);
    set_global_vertex_ids_of_tree_vertices (cmesh, global_tree_id, tree_indices.c_array(), num_tree_vertices);
```

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +t8_cmesh_vertex_conn_tree_to_vertex::set_global_vertex_ids_of_tree_vertices (const t8_cmesh_t cmesh,
Could we template this function so that it takes every iterable container like `std::vector` or `std::array?`

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +const t8_gloidx_t *
It is already unusable from C since it is in a class, so we can also get rid of the C array.
```suggestion
const std::array<t8_gloidx_t>
```

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +   *
Please add the proper docstring

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  /** Constructor from a cmesh where all the attributes are set. */
Please add the proper docstring

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +                                          const t8_gloidx_t *global_tree_vertices, const int num_vertices);
```suggestion
  template <t8_forward_iterator<t8_gloidx_t> TForwardIt>
  void
  set_global_vertex_ids_of_tree_vertices (const t8_cmesh_t, const t8_gloidx_t global_tree,
                                          const TForwardIt global_tree_vertices_begin, const TForwardIt global_tree_vertices_end);
```

with a `t8.hxx` containing
```cpp
  template <typename TValueType>
  concept t8_forward_iterator = std::forward_iterator<TValueType>;
```

2025-01-30 12:57 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  const t8_gloidx_t *
```suggestion
  const std::array<t8_gloidx_t>
```

2025-01-30 16:37 UTC, sandro-elsweijer reviewed
Another partial review

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +void
```suggestion
inline void
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +int
```suggestion
inline int
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +bool
```suggestion
inline bool
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +int
```suggestion
inline int
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +const t8_cmesh_vertex_conn_vertex_to_tree::tree_vertex_list&
```suggestion
inline const t8_cmesh_vertex_conn_vertex_to_tree::tree_vertex_list&
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +/* constructor from a given vertex to tree list. */
And the docstring is missing

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +void
```suggestion
inline void
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +t8_gloidx_t
```suggestion
inline t8_gloidx_t
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  const int
```suggestion
  inline int
```

2025-01-30 16:37 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +   * exists exactly once in the list.
I would also see a `std::unordered_map<tree_vertex_pair>` with the hash `ltreeid * T8_ECLASS_MAX_CORNERS + tree_vertex` here.

But since `T8_ECLASS_MAX_CORNERS ` is 8 and therefore a power of two, we could directly ditch the `tree_vertex_pair` and also the `std::unordered_map` and just use a `std::unordered_set<int64_t>` with the hash `ltreeid * 8 + tree_vertex`. The decomposition of the hash is then `ltreeid = hash - (hash % 8)` and `vertex_id = hash % 8` or using bitwise operation `ltreeid = hash - (hash & 0x7)` and `vertex_id = hash & 0x7`

2025-01-31 12:13 UTC, sandro-elsweijer requested changes
Last part of the review. Very nice PR and I like where this is going :)

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +                                          const t8_gloidx_t *global_tree_vertices, const int num_vertices);
Okay until this gets looked over again, `src/t8_types/t8_type.hxx` will be merged. Then we can put it there instead of creating a `t8.hxx`

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.cxx
> +
```suggestion

T8_EXTERN_C_BEGIN ();
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.cxx
> +}
```suggestion
}

T8_EXTERN_C_END ();
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.h
> +t8_cmesh_get_num_trees_at_vertex (const t8_cmesh_t cmesh, t8_gloidx_t global_vertex);
Docstrings

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +                                          const t8_gloidx_t *global_tree_vertices, const int num_vertices)
```suggestion
  template <t8_forward_iterator<t8_gloidx_t> TForwardIt>
  inline void
  set_global_vertex_ids_of_tree_vertices (const t8_cmesh_t, const t8_gloidx_t global_tree,
                                          const TForwardIt global_tree_vertices_begin, const TForwardIt global_tree_vertices_end);
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +                               const t8_gloidx_t *global_tree_vertices, const int num_vertices)
```suggestion
  template <t8_forward_iterator<t8_gloidx_t> TForwardIt>
  inline void
  set_global_vertices_of_tree (const t8_cmesh_t cmesh, const t8_gloidx_t global_tree,
                                const TForwardIt global_tree_vertices_begin, const TForwardIt global_tree_vertices_end)
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +
docstrings

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +  inline const t8_locidx_t *
```suggestion
  inline const std::array<t8_locidx_t>
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +  inline const t8_gloidx_t *
```suggestion
  inline const std::array<t8_gloidx_t>
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_connectivity.hxx
> +  inline const t8_gloidx_t *
```suggestion
  inline const std::array<t8_gloidx_t>
```

2025-01-31 12:13 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
> +/** */
Document

2025-01-31 12:13 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
> +TEST_P (cmesh_vertex_conn_ttv, DISABLED_get_global)
Why is the DISABLED keyword not working?

2025-01-31 12:13 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
> +TEST_P (cmesh_vertex_conn_ttv, DISABLED_get_global)
Why is the DISABLED keyword not working?

2025-01-31 12:13 UTC, sandro-elsweijer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
> +TEST_P (cmesh_vertex_conn_ttv, DISABLED_get_global)
Why is the DISABLED keyword not working?

2025-03-08 09:40 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +/* constructor from a given vertex to tree list. */
Docstring is in the header file.

2025-03-08 09:43 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +   * Note that this is very memory intensive, doubling the required memory. */
"Note that" is usually written without a comma.

2025-03-08 09:55 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  /** Constructor from a cmesh where all the attributes are set. */
Done.

2025-03-08 09:55 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +   *
Done

2025-03-08 09:58 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  const int
```suggestion
  inline const int
```

2025-03-08 09:58 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +int
```suggestion
inline const int
```

2025-03-08 09:59 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  const t8_gloidx_t *
```suggestion
  inline const t8_gloidx_t *
```

2025-03-08 10:00 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.hxx
> +  const int
```suggestion
  inline const int
```

2025-03-08 10:00 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> +  const int
```suggestion
  inline const int
```

2025-03-08 10:14 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +const t8_gloidx_t *
Tried this, does not work.

std::array is a constant (compile time) size array.
Since the number of vertices is determined at runtime, we cannot use it.

Since, we store the vertices as the raw data and return a pointer to this raw data to directly modify them, i argue to leave this be.

Alternatively: Return a vector that wraps around the storage. This will increase memory usage by adding the vector functionality and add runtime for constructing the wrapper.
But increases usability?
It will definitely increase type-safety.

Would try if i still have time at the end.

2025-03-08 10:24 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> +t8_cmesh_vertex_conn_vertex_to_tree::sort_list_by_tree_id ()
I decided against inlining this function since

a) it is a runtime intensive function using std::sort. So no expected gain from inlining
b) Inlining would require to move it to the header and with it "t8_cmesh_tree_vertex_pair_compare". It does not feel right to do so.

2025-03-08 10:32 UTC, holke commented
Note: Inlining get_global_vertices requires us to move the implementation in the header, in turn requiring us to include "t8_cmesh_types" in the header.
Since t8_cmesh_types is an internal header that must not be exposed to the user, this means that now "t8_cmesh_vertex_conn_tree_to_vertex.hxx" is then definitely an internal header.
This is okay, since the user interface/public header should only be "t8_cmesh_vertex_connectivity.hxx" or even only "t8_cmesh.hxx".

2025-03-08 11:02 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> +/** \file t8_cmesh_vertex_conn_vertex_to_tree.hxx
Done

2025-03-08 11:05 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> + *  tree_id_A == tree_id_B and vertex_id_A < vertex_id_B */
Do you mean: 
a) Add doxygen style or
b) Improve the documentation

If a) then note that this is in a .cxx file where we generally do not generate doxygen strings.
If b) please elaborate what i should explain better.

2025-03-08 11:08 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> + * I_0 does not have to be 0 and I_N does not have to be N.
Yes, if we look to the future towards partitioned cmeshes, then portions will be missing and since we do not partition by vertex id but by tree id, the vertex ids will be all over the place.

Additionally, we are note guaranteed to get a contiguous list as input and
if we write our own global vertex id assignement function we would have it way easier if we do not have to make it contiguous.

2025-03-08 13:05 UTC, holke commented
- address code review comments
- clean up
- documentation
- Fixed bugs so that now the tests pass (at least i hope, the tests are not finished running while i write this)
- did not implement the optimization suggestion (i.e. unstructured map, etc) due to time reasons
- I was not sure if we can update this branch with main or not, so i did not do it for now.

If you are happy with the functionality i suggest to merge this now.
We can add the suggested optimizations later (but should make issues out of them before they get lost).

2025-03-08 13:09 UTC, holke commented
removed draft status

2025-03-09 15:44 UTC, sandro-elsweijer requested changes

2025-03-09 15:44 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_tree_to_vertex.cxx
> +    for (auto &[tree_index, vertex_index] : vertex_list) {
This is still open

2025-03-09 15:44 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> + * I_0 does not have to be 0 and I_N does not have to be N.
Okay, but we still should remove the noted during development after the development is finished :)

2025-03-09 15:44 UTC, sandro-elsweijer commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.cxx
> + *  tree_id_A == tree_id_B and vertex_id_A < vertex_id_B */
I meant a). Yes we usually do not use docstrings in cxx files, since they have a proper one in the hxx. But since this function is static I think it should have a proper doxygen formatted docstring here. Docstrings are not just for users, but for us devs as well

2025-03-14 12:39 UTC, holke commented
https://github.com/DLR-AMR/t8code/pull/960#discussion_r1986352073

Addressed this

2025-03-14 12:40 UTC, holke commented
In order to clean up our folder structure i moved all cmesh vertex connectivity related cmesh files into a subfolder "src/t8_cmesh/t8_cmesh_vertex_connectivity/".
This declutters the src/t8_cmesh directory.

2025-03-14 12:43 UTC, holke commented
https://github.com/DLR-AMR/t8code/pull/960#discussion_r1986352021

Resolved this by merging the dev notes with the actual class documentation.

2025-03-14 12:44 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> +   * Currently, \a cmesh has to be replicated. */
Done

2025-03-14 12:46 UTC, holke commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn_tree_to_vertex.cxx
> +TEST_P (cmesh_vertex_conn_ttv, DISABLED_get_global)
I dont know why it wasnt properly working. Will check again.

2025-03-24 12:14 UTC, holke commented
TODO: @holke reconstruct the DISABLED test, what was happening? Why did i add the #0? Can we ENABLE the test now?

2025-04-15 11:33 UTC, holke commented
> TODO: @holke reconstruct the DISABLED test, what was happening? Why did i add the #0? Can we ENABLE the test now?

No, we cannot enable the tests now.
The disabled tests are part of a test suite that would check all cmesh test examples, but cannot be used currently because we cannot add attributes when deriving a cmesh.

However, i removed the DISABLED keyword, because the tests were never registered with gtest in the first place, but (correctly) commented out with #if 0. Which is not the usual way to do it - we should always opt for DISABLED - but in this case necessary, since the tests refer to a whole Test suite that is not run and to avoid code copying the preprocessor is the better alternative here.

2025-04-15 14:42 UTC, lukasdreyer commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
> +/* In this file we test TODO: document */
Can you please add a description of what this test is testing. This is the first place where users look for how to use a new feature, if there is no tutorial.

2025-04-16 09:25 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> +   * \return The list of global tree ids and local vertex ids of \a global_vertex_id.
There is a documentation mismatch.
This says "list of global tree ids" but the return value tree_vertex_list stores local ids.
@holke double check this.

2025-04-16 11:56 UTC, holke commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
> +/* In this file we test TODO: document */
good catch, will do

2025-04-23 12:14 UTC, holke commented on test/t8_cmesh/t8_gtest_cmesh_vertex_conn.cxx
> +/* In this file we test TODO: document */
Done

2025-04-30 14:27 UTC, holke commented on src/t8_cmesh/t8_cmesh_vertex_connectivity/t8_cmesh_vertex_conn_vertex_to_tree.hxx
> +   * \return The list of global tree ids and local vertex ids of \a global_vertex_id.
double checked it. The comment is wrong, we are storing local tree ids.
Corrected the comment.

2025-05-05 13:54 UTC, sandro-elsweijer submitted a review, later dismissed

2025-05-05 15:09 UTC, sandro-elsweijer approved these changes

2025-05-05 16:04 UTC, merged